language: node_js

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

before_install:
  - npm i npm@latest -g

script: make travis

sudo: false

notifications:
  slack:
    secure: BiCHWsLTzlEd6MjRZY27BgmtCA3DmBFo5jcSsjSqmInbgla0lzDAA40xfIKTswIwK0pzuQdVaanl5Jy78wul0lfxpa5LLWX/bQmR1LGrygphC5tFG7GDM9Hdjatce5XEYVsSAUddNFEVQtMEUuUkSOiUll7kRq4LQtvAiIy1isk=
